itineraryplanner/config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    #
    url(r'^',
        include('itineraryplanner.itineraries.urls', namespace='itineraries')), 
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('itineraryplanner.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # URls for Google Examples App
    url(r'^googleExamples/',
        include('itineraryplanner.google_examples.urls', namespace='google-examples')),
    url(r'^itineraryPlanner/',
        include('itineraryplanner.itineraries.urls', namespace='itineraries')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

itineraryplanner/itineraryplanner/google_examples/urls.py
from django.conf.urls import url

from .views import ReactAttempt, ExamplesMenu, AutoCompleteExample, DistancesExample, SearchBoxExample, SearchAttempt

urlpatterns = [
    url(regex=r"^$",
        view=ExamplesMenu.as_view(),
        name="menu"),
    url(regex=r"^autocomplete/",
        view=AutoCompleteExample.as_view(),
        name="autocomplete"),
    url(regex=r"^distances/",
        view=DistancesExample.as_view(),
        name="distances"),
    url(regex=r"^searchbox/",
        view=SearchBoxExample.as_view(),
        name="searchbox"),
    url(regex=r"^attempt/",
        view=SearchAttempt.as_view(),
        name="attempt"),
    url(regex=r"^react/",
        view=ReactAttempt.as_view(),
        name="react"),
]

itineraryplanner/itineraryplanner/itineraries/urls.py
from django.conf.urls import url

from .views import PlacesOfInterestView

urlpatterns = [
    url(regex=r"^$",
        view=PlacesOfInterestView.as_view(),
        name="itineraryPicker"),
]

itineraryplanner/itineraryplanner/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

itineraryplanner/itineraryplanner/google_examples/models.py
from django.db import models

# Create your models here.

itineraryplanner/itineraryplanner/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

itineraryplanner/itineraryplanner/google_examples/views.py
from django.views.generic import TemplateView
# Create your views here.
class ExamplesMenu(TemplateView):
    template_name = 'google-examples/menu.html'

class AutoCompleteExample(TemplateView):
    template_name = 'google-examples/autocomplete.html'

class DistancesExample(TemplateView):
    template_name= 'google-examples/distances.html'

class SearchBoxExample(TemplateView):
    template_name = 'google-examples/searchbox.html'

class SearchAttempt(TemplateView):
    template_name = 'google-examples/attempt.html'

class ReactAttempt(TemplateView):
    template_name = 'google-examples/reactattempt.html'

itineraryplanner/itineraryplanner/itineraries/views.py
"""
This view receives the input from the user. 
Validates it and creates a POI or updates it.
Then creates the ItineraryStep for each possible combination.
Adds everything to the Itinerary model and sends it to the 
server to compute the desired TOUR.
"""
# pylint: disable=E1101
import json
import pprint
import re
import time

import googlemaps
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import FormView

from ..utils.helpers import (convert_plan, create_pddl_problem, run_subprocess,
                             write_pddl_file, remove_special_chars_from_name)
from .forms import PlacesOfInterestForm
from .models import Itinerary, ItineraryStep, PlaceOfInterest, Preferences

#gmaps = googlemaps.Client(key='AIzaSyBucexwP3IjpafwcJVPR3KtRnhqk-1sa00')
gmaps = googlemaps.Client(key='AIzaSyAxJ5w-FZlmrRB6VGyQdD2U18Oqr0QTLxs')


class PlacesOfInterestView(FormView):
    """
    View for receiving the user input and convert
    it to a POI object for the database.
    1. Checks if the POI exists or create it.
    2. Also gets the distances between each point between them.
    3. Saves both PlacesOfInterest and ItineraryStep models.
    4. Also saves everything to the Itinerary model to run it.
    """
    template_name = 'itineraries/index.html'
    form_class = PlacesOfInterestForm
    success_url = reverse_lazy('itineraries:itineraryPicker')

    def render_to_json_response(self, context, **response_kwargs):
        """Render a json response of the context."""

        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super(PlacesOfInterestView,
                        self).get_context_data(**kwargs)
        context['success_url'] = self.success_url
        return context

    def post(self, request, *args, **kwargs):
        """
        TBD
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_invalid(self, form):
        print("The form is invalid. As such the program can't continue.")
        return super(PlacesOfInterestView, self).form_invalid(form)

    def form_valid(self, form):
        response = super(PlacesOfInterestView, self).form_valid(form)
        # This method is called when valid form data has been POST-ed.
        # It should return an HttpResponse.
        # Contains the list of places the user wants to visit.
        places_to_visit = json.loads(form.cleaned_data['placesToVisit'])
        # Preferences are priority of places, visit for, end at and start at.
        preferences = json.loads(form.cleaned_data['preferences'])
        # Properties refers to the sleep time, wake up time and transporation methods used.
        properties = json.loads(form.cleaned_data['properties'])
        # Get the user preferente for running the Plan.

        run_plan_for = int(properties['runFor'])
        awaken_times = {
            'awaken': properties['wakeUpTime'],
            'not_awaken': properties['sleepTime']
        }
        transporation_methods = properties['methods']
        print("Printing Properties.\n", properties)
        print("Printing Run For.\n", run_plan_for)
        #distanceMatrixJson = form.cleaned_data['distanceMatrix']
        #distanceMatrixObject = json.loads(distanceMatrixJson)
        created_places = []
        for place in places_to_visit:
            # To DEBUG remove comments
            # print("Place with id: {0} and title: {2} \n Coordinates lat:{3},lng:{4}.\
            # \n Opens at:{5} and Closes at:{6}  ".format(
            #     place['place_id'],
            #     place['is_hotel'],
            #     place['name'],
            #     place['lat'],
            #     place['lng'],
            #     place['opens'],
            #     place['closes']
            # ))
            # we first try update the place in case it exists.
            # otherwise we just create it and carry on with the
            # relations with other Models in the database
            opens = place['opens'] or ""
            closes = place['closes'] or ""
            obj, created = PlaceOfInterest.objects.update_or_create(  # pylint: disable=W0612
                place_id=place['place_id'],
                defaults={
                    "is_hotel": place['is_hotel'],
                    "name": remove_special_chars_from_name(place['name']),
                    "lat": place['lat'],
                    "lng": place['lng'],
                    "opens": opens,
                    "closes": closes,
                }
            )
            # TODO:not the most elegant solution for the preference problem
            created_places.append(obj)
            # To DEBUG remove comments
            # if created:
            #     print("'{}' was created successfully".format(obj.name))
            # else:
            #     print("'{0}' was already in the database with id={1}".format(
            #         obj.name, obj.place_id))
            # print(obj, ", was created?: ", created)
        # Create an Itinerary Object to hold the tour.
        itinerary = Itinerary()
        # Initialize start and end at variables to store the itinerary initial and ending
        start_at = ''
        end_at = ''
        # get the mentioned places from the preferences
        for key, value in preferences.items():
            if value['startAt'] != False:
                start_at = value['startAt']
            if value['endAt'] != False:
                end_at = value['endAt']
        # set the initial and ending POI
        itinerary.initialPOI = PlaceOfInterest.objects.get(place_id=start_at)
        itinerary.endingPOI = PlaceOfInterest.objects.get(place_id=end_at)
        itinerary.save()
        #import pdb;pdb.set_trace()
        for place in created_places:
            visit_for = preferences[place.place_id]['visitFor']
            priority = preferences[place.place_id]['priority']
            Preferences.objects.create(
                itinerary=itinerary,
                place=place,
                visitFor=visit_for,
                priority=priority,
            )
        # TODO: Fix this as it runs more than needed.
        # Traverse all the possible origins
        GOOGLE_MAPS_START = time.monotonic()
        for origin in places_to_visit:
            # Traverse all the possible destinations
            for destination in places_to_visit:
                # for each destination check that is not the same as origin
                # then save the object as an Itinerary Step and compute duration of trip
                if destination != origin:
                    origin_poi = PlaceOfInterest.objects.get(place_id=origin['place_id'])
                    destination_poi = PlaceOfInterest.objects.get(place_id=destination['place_id'])
                    # Call Google distance matrix with user's parameters
                    if transporation_methods:
                        for key, value in transporation_methods.items():
                            if value:
                                method_choice = {
                                    'walking': ItineraryStep.METHOD_CHOICES.WALK,
                                    'bicycling': ItineraryStep.METHOD_CHOICES.BIKE,
                                    'driving': ItineraryStep.METHOD_CHOICES.CAR,
                                    'transit': ItineraryStep.METHOD_CHOICES.TRANSIT,
                                }
                                dmx = gmaps.distance_matrix(
                                    origins='place_id:{}'.format(origin['place_id']),
                                    destinations='place_id:{}'.format(destination['place_id']),
                                    mode=key,
                                    language="english"
                                )
                                print("End of the API call.")
                                it_step = ItineraryStep.objects.create(
                                    origin=origin_poi,
                                    destination=destination_poi,
                                    itinerary=itinerary,
                                    # TODO: (driving, walking, bicycling, transit)
                                    method=method_choice[key]
                                )
                                duration = dmx['rows'][0]['elements'][0]['duration']['value']
                                it_step.duration = duration
                                it_step.save()

                # To DEBUG remove comments
                # else:
                #     print("Destination:{0} and Origin:{0} are the same".format(destination, origin))
        GOOGLE_TIME_ELAPSED = time.monotonic()-GOOGLE_MAPS_START
        print("GOOGLE API TOOK :",GOOGLE_TIME_ELAPSED)
        '''
        all_distances = itinerary.get_distance_matrix_places_format()
        dmx = gmaps.distance_matrix(
            origins=all_distances,
            destinations=all_distances,
            mode='walking',
            language='english'
        )
        print("Got distances. {} Elements.\n{}".format(len(dmx),dmx))
        for outer in enumerate(all_distances):
            for inner in enumerate(all_distances):
                if not outer[1] == inner[1]:
                    it_step = ItineraryStep.objects.get(itinerary=itinerary,origin__place_id=outer[1][9:],destination__place_id=inner[1][9:])
                    it_step.duration = dmx['rows'][outer[0]]['elements'][inner[0]]['duration']['value']
                    it_step.save()
                    #print("FROM ", outer[1][9:]," TO ",inner[1][9:])
                    #print(dmx['rows'][outer[0]]['elements'][inner[0]]['duration']['value'])
        '''

itineraryplanner/itineraryplanner/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

itineraryplanner/itineraryplanner/templates/google-examples/attempt.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- google api key AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo -->
    <title>Auto-complete Map</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/searchbox.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid wrapper">
        <div class="row">
            <div id="places" class="col-lg-4 d-flex flex-column p-0">
                <input id="pac-input" class="controls" type="text" placeholder="Search Box">
                <div id="searchedPlaces">
                    <form id="placesSelectedForm" method="POST" action="">
                        
                    </form>
                </div>
            </div>
            {% comment %}
                Everything map related goes here
            {% endcomment %}
            <div id="map" class="col-lg-8"></div>
            <div style="display: none">
                <div id="info-content">
                    <table>
                        <tr id="iw-url-row" class="iw_table_row">
                            <td id="iw-icon" class="iw_table_icon"></td>
                            <td id="iw-url"></td>
                        </tr>
                        <tr id="iw-address-row" class="iw_table_row">
                            <td class="iw_attribute_name">Address:</td>
                            <td id="iw-address"></td>
                        </tr>
                        <tr id="iw-phone-row" class="iw_table_row">
                            <td class="iw_attribute_name">Telephone:</td>
                            <td id="iw-phone"></td>
                        </tr>
                        <tr id="iw-rating-row" class="iw_table_row">
                            <td class="iw_attribute_name">Rating:</td>
                            <td id="iw-rating"></td>
                        </tr>
                        <tr id="iw-website-row" class="iw_table_row">
                            <td class="iw_attribute_name">Website:</td>
                            <td id="iw-website"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div><!-- end of row-->
    </div> <!-- end of wrapper-->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap/tether/tether.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo&libraries=places"></script>
    <script type="text/javascript" src="{% static 'js/attempt.js' %}"></script>
</body>

</html>

itineraryplanner/itineraryplanner/templates/google-examples/autocomplete.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- google api key AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo -->
    <title>Auto-complete Map</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/autocomplete-map.css' %}" rel="stylesheet">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo&libraries=places"></script>
    <script type="text/javascript" src="{% static 'js/autocomplete-map.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap/tether/tether.min.js' %}"></script>
</head>

<body>
    <div class="container-fluid wrapper">
        <div class="row">
            <div id="activities" class="col-lg-4 d-flex flex-column p-0">
                <div id="locationField">
                    <h3 class="p-2">Find Attractions in:</h3><br>
                    <input id="autocomplete" placeholder="Enter a city" type="text" />
                </div>
                <div id="controls">
                    <select id="country">
                        <option value="all">All</option>
                        <option value="au">Australia</option>
                        <option value="br">Brazil</option>
                        <option value="ca">Canada</option>
                        <option value="fr">France</option>
                        <option value="de">Germany</option>
                        <option value="mx">Mexico</option>
                        <option value="nz">New Zealand</option>
                        <option value="it">Italy</option>
                        <option value="za">South Africa</option>
                        <option value="es">Spain</option>
                        <option value="pt">Portugal</option>
                        <option value="us">U.S.A.</option>
                        <option value="uk" selected>United Kingdom</option>
                    </select>
                </div>
                <div id="listing" style="border:1px solid">
                    <table id="resultsTable">
                        <tbody id="results"></tbody>
                    </table>
                </div>
            </div>
            

            <div id="map" class="col-lg-8"></div>
            <div style="display: none">
                <div id="info-content">
                    <table>
                        <tr id="iw-url-row" class="iw_table_row">
                            <td id="iw-icon" class="iw_table_icon"></td>
                            <td id="iw-url"></td>
                        </tr>
                        <tr id="iw-address-row" class="iw_table_row">
                            <td class="iw_attribute_name">Address:</td>
                            <td id="iw-address"></td>
                        </tr>
                        <tr id="iw-phone-row" class="iw_table_row">
                            <td class="iw_attribute_name">Telephone:</td>
                            <td id="iw-phone"></td>
                        </tr>
                        <tr id="iw-rating-row" class="iw_table_row">
                            <td class="iw_attribute_name">Rating:</td>
                            <td id="iw-rating"></td>
                        </tr>
                        <tr id="iw-website-row" class="iw_table_row">
                            <td class="iw_attribute_name">Website:</td>
                            <td id="iw-website"></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div><!-- end of row-->
    </div> <!-- end of wrapper-->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap/bootstrap.min.js' %}"></script>
</body>

</html>

itineraryplanner/itineraryplanner/templates/google-examples/distances.html
<!DOCTYPE html>
<html>
  <head>
    <title>Distance Matrix service</title>
    <style>
      #right-panel {
        font-family: 'Roboto','sans-serif';
        line-height: 30px;
        padding-left: 10px;
      }

      #right-panel select, #right-panel input {
        font-size: 15px;
      }

      #right-panel select {
        width: 100%;
      }

      #right-panel i {
        font-size: 12px;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #map {
        height: 100%;
        width: 50%;
      }
      #right-panel {
        float: right;
        width: 48%;
        padding-left: 2%;
      }
      #output {
        font-size: 11px;
      }
    </style>
  </head>
  <body>
    <div id="right-panel">
      <div id="inputs">
        <pre>
var origin1 = {lat: 55.930, lng: -3.118};
var origin2 = 'Greenwich, England';
var destinationA = 'Stockholm, Sweden';
var destinationB = {lat: 50.087, lng: 14.421};
        </pre>
      </div>
      <div>
        <strong>Results</strong>
      </div>
      <div id="output"></div>
    </div>
    <div id="map"></div>
    <script>
      function initMap() {
        var bounds = new google.maps.LatLngBounds;
        var markersArray = [];

        //var origin1 = {lat: 55.93, lng: -3.118};
        var origin1 = 'wembley stadium'
        var destinationC = 'Greenwich, England';
        var destinationA = 'Stockholm, Sweden';
        var destinationB = {lat: 50.087, lng: 14.421};
        var destinationArray = [
            'king\'s college london',
            'university college london',
            'king\'s cross',
        ]

        var destinationIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=D|FF0000|000000';
        var originIcon = 'https://chart.googleapis.com/chart?' +
            'chst=d_map_pin_letter&chld=O|FFFF00|000000';
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 55.53, lng: 9.4},
          zoom: 10
        });
        var geocoder = new google.maps.Geocoder;

        var service = new google.maps.DistanceMatrixService;
        service.getDistanceMatrix({
          origins: destinationArray,
          //destinations: [destinationA, destinationB, destinationC],
          destinations:destinationArray,
          travelMode: 'WALKING',
          unitSystem: google.maps.UnitSystem.METRIC,
          avoidHighways: false,
          avoidTolls: false
        }, function(response, status) {
          if (status !== 'OK') {
            alert('Error was: ' + status);
          } else {
            var originList = response.originAddresses;
            var destinationList = response.destinationAddresses;
            var outputDiv = document.getElementById('output');
            outputDiv.innerHTML = '';
            deleteMarkers(markersArray);

            var showGeocodedAddressOnMap = function(asDestination) {
              var icon = asDestination ? destinationIcon : originIcon;
              return function(results, status) {
                if (status === 'OK') {
                  map.fitBounds(bounds.extend(results[0].geometry.location));
                  markersArray.push(new google.maps.Marker({
                    map: map,
                    position: results[0].geometry.location,
                    icon: icon
                  }));
                } else {
                  alert('Geocode was not successful due to: ' + status);
                }
              };
            };

            for (var i = 0; i < originList.length; i++) {
              var results = response.rows[i].elements;
              console.log(results);
              geocoder.geocode({'address': originList[i]},
                  showGeocodedAddressOnMap(false));
              for (var j = 0; j < results.length; j++) {
                geocoder.geocode({'address': destinationList[j]},
                    showGeocodedAddressOnMap(true));
                outputDiv.innerHTML += originList[i] + ' to ' + destinationList[j] +
                    ': ' + results[j].distance.text + ' in ' +
                    results[j].duration.text + ' (' + results[j].duration.value +') ' + '<br>';
              }
            }
          }
        });
      }

      function deleteMarkers(markersArray) {
        for (var i = 0; i < markersArray.length; i++) {
          markersArray[i].setMap(null);
        }
        markersArray = [];
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo&callback=initMap">
    </script>
  </body>
</html>

itineraryplanner/itineraryplanner/templates/google-examples/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- google api key AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo -->
        <title>Itinerary Planner</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
        <link href="css/style.css" rel="stylesheet">
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB62WXl60F8rx74hDmKjj_sBJRwu5Wgnlo&libraries=places"></script>
        <script type="text/javascript" src="js/place-search.js"></script>
        <script type="text/javascript" src="js/bootstrap/tether/tether.min.js"></script>
    </head>
    <body>
        <div class="container-fluid wrapper">
            <div class="row">
                <div class="col-md-3">Test</div>
                <div id="map" class="col-md-9">Loading map...</div>
            </div>
        </div>
        <script type="text/javascript" src="js/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="js/bootstrap/bootstrap.min.js"></script>
    </body>
</html>

itineraryplanner/itineraryplanner/templates/google-examples/menu.html
{% extends "base.html" %}

{% block content %}

<h2>Direct Links to Google Maps examples</h2>
<ul>
    <li><a href="{% url 'google-examples:autocomplete' %}">Autocomplete</a></li>
    <li><a href="{% url 'google-examples:distances' %}">Distances</a></li>
    <li><a href="{% url 'google-examples:searchbox' %}">SearchBox</a></li>
</ul>

{% endblock %}